[package]
name = "fetch-appveyor-build-time"
version = "0.1.0"
authors = ["kennytm <kennytm@gmail.com>"]

[dependencies]
regex = "0.2"
reqwest = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
